services:
  agent:
    #image: zabbix/zabbix-agent2:${ZBX_IMAGE_TAG}
    image: zabbix/zabbix-agent2:alpine-7.0-latest
    container_name: zabbix-agent2
    restart: unless-stopped

    # Let the agent see host network interfaces and listen for passive checks
    network_mode: host

    # Needed for reading host metrics and some /proc features (LLD, net, etc.)
    privileged: true

    environment:
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
      - ZBX_SERVER_ACTIVE=${ZBX_SERVER_HOST}
      - ZBX_HOSTNAME=${ZBX_HOSTNAME}
      - ZBX_DEBUGLEVEL=${ZBX_DEBUGLEVEL}

    # Mount host filesystems so Agent can read system metrics,
    # and the Docker socket so Agent's Docker plugin can collect container metrics.
    volumes:
      - /:/hostfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock

    # Grant the container's zabbix user membership to the host's docker group.
    # This is key for docker.sock access without changing host users.
    group_add:
      - "${DOCKER_GID}"
