services:
  agent:
    image: zabbix/zabbix-agent2:alpine
    container_name: zabbix-agent2
    restart: unless-stopped

    # To see host interfaces & bridges and collect host metrics
    network_mode: host
    privileged: true

    environment:
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
      - ZBX_SERVER_ACTIVE=${ZBX_SERVER_HOST}
      - ZBX_HOSTNAME=${ZBX_HOSTNAME}
      - ZBX_DEBUGLEVEL=${ZBX_DEBUGLEVEL}

    # Mounts for host/Docker metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/dev

    # Let the zabbix user talk to Docker via the socket
    group_add:
      - "${DOCKER_GID}"
